# Generated by Django 3.2 on 2022-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('airline_id', models.IntegerField(db_index=True, unique=True)),
                ('fuel_capacity', models.FloatField()),
                ('passengers', models.IntegerField(default=1)),
                ('airline_fuel_consumption', models.FloatField()),
                ('passenger_fuel_consumption', models.FloatField()),
                ('total_fuel_consumption', models.FloatField()),
                ('maximum_travel_time', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_multiplier', models.IntegerField(default=200)),
                ('consumption_multiplier', models.FloatField(default=0.08)),
                ('passenger_consumption_multiplier', models.FloatField(default=0.002)),
            ],
        ),
    ]
