# Generated by Django 3.2 on 2022-01-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='airline_fuel_consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airline',
            name='fuel_capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airline',
            name='passenger_fuel_consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airline',
            name='total_fuel_consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='config',
            name='consumption_multiplier',
            field=models.FloatField(default=0.08),
        ),
        migrations.AlterField(
            model_name='config',
            name='passenger_consumption_multiplier',
            field=models.FloatField(default=0.002),
        ),
    ]
